// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW_9Y1CODc4evXz0i9jVh9cSE78H8k934',
    appId: '1:475578077387:web:2a622238630e59a06e0b4e',
    messagingSenderId: '475578077387',
    projectId: 'taskify-3200e',
    authDomain: 'taskify-3200e.firebaseapp.com',
    storageBucket: 'taskify-3200e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy4lonmNFsYfQdzkvcCbgfVaUjXeCnPwI',
    appId: '1:475578077387:android:63f3351a73cd21a56e0b4e',
    messagingSenderId: '475578077387',
    projectId: 'taskify-3200e',
    storageBucket: 'taskify-3200e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXDDljZ5RcmDxO8HLOa0TceAdOl3npucE',
    appId: '1:475578077387:ios:cdd4fab84c78bbd86e0b4e',
    messagingSenderId: '475578077387',
    projectId: 'taskify-3200e',
    storageBucket: 'taskify-3200e.firebasestorage.app',
    iosBundleId: 'nathan.com.taskifyProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXDDljZ5RcmDxO8HLOa0TceAdOl3npucE',
    appId: '1:475578077387:ios:cdd4fab84c78bbd86e0b4e',
    messagingSenderId: '475578077387',
    projectId: 'taskify-3200e',
    storageBucket: 'taskify-3200e.firebasestorage.app',
    iosBundleId: 'nathan.com.taskifyProject',
  );
}
